server.port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/docker
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  log_path: /var/logs